# Generated by Django 2.2.4 on 2019-09-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0002_auto_20190908_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField()),
                ('icon', models.ImageField(upload_to='media/images/project/icon')),
                ('short_desc', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
        ),
    ]
