# Generated by Django 2.2.4 on 2019-09-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0004_auto_20190909_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog',
        ),
        migrations.AddField(
            model_name='blog',
            name='blog1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='blogl',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='image2',
            field=models.ImageField(blank=True, upload_to='media/images/blog'),
        ),
        migrations.AddField(
            model_name='blog',
            name='image3',
            field=models.ImageField(blank=True, upload_to='media/images/blog'),
        ),
        migrations.AddField(
            model_name='blog',
            name='image4',
            field=models.ImageField(blank=True, upload_to='media/images/blog'),
        ),
        migrations.AddField(
            model_name='project',
            name='ss1',
            field=models.ImageField(blank=True, upload_to='media/images/project/icon'),
        ),
        migrations.AddField(
            model_name='project',
            name='ss2',
            field=models.ImageField(blank=True, upload_to='media/images/project/icon'),
        ),
        migrations.AddField(
            model_name='project',
            name='ss3',
            field=models.ImageField(blank=True, upload_to='media/images/project/icon'),
        ),
        migrations.AddField(
            model_name='project',
            name='ss4',
            field=models.ImageField(blank=True, upload_to='media/images/project/icon'),
        ),
    ]
