# Generated by Django 2.2.4 on 2019-09-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0005_auto_20190909_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image4',
            field=models.TextField(blank=True),
        ),
    ]
