# Generated by Django 2.2.4 on 2019-09-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0006_auto_20190909_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image2',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image3',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image4',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
