# Generated by Django 2.2.4 on 2019-09-10 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0008_auto_20190909_2031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
