# Generated by Django 2.2.4 on 2019-09-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20190903_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='topProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='media/images/icons')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('site', models.URLField(max_length=500)),
            ],
        ),
    ]
