# Generated by Django 2.2.4 on 2019-09-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_topprojects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topprojects',
            name='site',
            field=models.URLField(max_length=300),
        ),
    ]
