# Generated by Django 2.2.4 on 2019-09-08 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_feturette'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='feturette',
            new_name='featurette',
        ),
    ]
