# Generated by Django 2.2.4 on 2019-09-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_auto_20190909_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurette',
            name='f1_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='featurette',
            name='f1_img',
            field=models.ImageField(blank=True, upload_to='media/images/featurette'),
        ),
        migrations.AlterField(
            model_name='featurette',
            name='f1_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='featurette',
            name='f2_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='featurette',
            name='f2_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='featurette',
            name='f3_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='featurette',
            name='f3_img',
            field=models.ImageField(blank=True, upload_to='media/images/featurette'),
        ),
        migrations.AlterField(
            model_name='featurette',
            name='f3_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
