# Generated by Django 2.2.4 on 2019-09-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_auto_20190910_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurette',
            name='site',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='featurette',
            name='site2',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='featurette',
            name='site3',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
