# Generated by Django 2.2.4 on 2019-09-13 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_auto_20190913_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featurette',
            name='f2_desc',
        ),
        migrations.RemoveField(
            model_name='featurette',
            name='f2_img',
        ),
        migrations.RemoveField(
            model_name='featurette',
            name='f2_stxt',
        ),
        migrations.RemoveField(
            model_name='featurette',
            name='f2_title',
        ),
        migrations.RemoveField(
            model_name='featurette',
            name='f3_desc',
        ),
        migrations.RemoveField(
            model_name='featurette',
            name='f3_img',
        ),
        migrations.RemoveField(
            model_name='featurette',
            name='f3_stxt',
        ),
        migrations.RemoveField(
            model_name='featurette',
            name='f3_title',
        ),
        migrations.RemoveField(
            model_name='featurette',
            name='site2',
        ),
        migrations.RemoveField(
            model_name='featurette',
            name='site3',
        ),
    ]
