# Generated by Django 2.2.4 on 2019-09-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_auto_20190913_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurette',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
